'use strict';

export const APP = {
	TAB: 'APP.TAB',
	'NAVIGATION':'APP.NAVIGATION'
}

export const GAME = {
	INFO: 'GAME.INFO',
	DETAIL:'GAME.DETAIL',
	STANDING:'GAME.STANDING'
}

export const TEAM = {
	RANK: 'TEAM.RANK',
	INFO: 'TEAM.INFO',
	DETAIL: 'TEAM.DETAIL'
}

export const PLAYER = {
	LIST: 'PLAYER.LIST',
	DETAIL: 'PLAYER.DETAIL',
	LOG: 'PLAYER.LOG',
	RECENT: 'PLAYER.RECENT'
}